---
listen: :443
tls:
  cert: /certs/cert_public
  key: /certs/cert_private
auth:
  type: password
  password: 69b7087ce42bae42
quic:
  initStreamReceiveWindow: 26843545
  maxStreamReceiveWindow: 26843545
  initConnReceiveWindow: 67108864
  maxConnReceiveWindow: 67108864
masquerade:
  type: proxy
  proxy:
    url: https://news.ycombinator.com/
    rewriteHost: true
speedTest: false
disableUDP: false
...
